<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="28" passed="13" failed="10" skipped="5">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-05-30T09:20:14Z" name="Default suite" finished-at="2018-05-30T09:24:52Z" duration-ms="278026">
    <groups>
      <group name="officeapps">
        <method signature="TestReportIncident.reportExcelIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportExcelIncident" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportOutlookIncidentBrowser()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportOutlookIncidentBrowser" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportOutlookIncidentIcon()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportOutlookIncidentIcon" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportPowerpointIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportPowerpointIncident" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportWordIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportWordIncident" class="testcases.TestReportIncident"/>
      </group> <!-- officeapps -->
      <group name="skype">
        <method signature="TestReportIncident.reportSkypeCredentials()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportSkypeCredentials" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportSkypeErrorMessage()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportSkypeErrorMessage" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportSkypeFunctionalities()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportSkypeFunctionalities" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportSkypeOther()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportSkypeOther" class="testcases.TestReportIncident"/>
      </group> <!-- skype -->
      <group name="officeapp">
        <method signature="TestReportIncident.reportOfficeAppIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportOfficeAppIncident" class="testcases.TestReportIncident"/>
      </group> <!-- officeapp -->
      <group name="ip phone">
        <method signature="TestReportIncident.ipPhoneFunctionalities()[pri:0, instance:testcases.TestReportIncident@7690781]" name="ipPhoneFunctionalities" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.ipPhoneLogonCredentials()[pri:0, instance:testcases.TestReportIncident@7690781]" name="ipPhoneLogonCredentials" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.ipPhoneLogonErrorMessage()[pri:0, instance:testcases.TestReportIncident@7690781]" name="ipPhoneLogonErrorMessage" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.ipPhoneOther()[pri:0, instance:testcases.TestReportIncident@7690781]" name="ipPhoneOther" class="testcases.TestReportIncident"/>
      </group> <!-- ip phone -->
      <group name="citrix">
        <method signature="TestReportIncident.reportCitrixOneApp()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportCitrixOneApp" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportCitrixOtherOneApp()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportCitrixOtherOneApp" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportCitrixOtherSeveralApps()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportCitrixOtherSeveralApps" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportCitrixSeveralApps()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportCitrixSeveralApps" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportCitrixOtherAllApps()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportCitrixOtherAllApps" class="testcases.TestReportIncident"/>
      </group> <!-- citrix -->
      <group name="business app">
        <method signature="TestReportIncident.reportBPC()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportBPC" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportClickView()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportClickView" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportClockWorks()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportClockWorks" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportLyris()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportLyris" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportMailChimp()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportMailChimp" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportMobaTime()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportMobaTime" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportProConcept()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportProConcept" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportScorecards()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportScorecards" class="testcases.TestReportIncident"/>
        <method signature="TestReportIncident.reportHRForms()[pri:0, instance:testcases.TestReportIncident@7690781]" name="reportHRForms" class="testcases.TestReportIncident"/>
      </group> <!-- business app -->
    </groups>
    <test started-at="2018-05-30T09:20:14Z" name="Default test" finished-at="2018-05-30T09:24:52Z" duration-ms="278026">
      <class name="testcases.TestReportIncident">
        <test-method is-config="true" signature="loadPage()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:14Z" name="loadPage" finished-at="2018-05-30T09:20:25Z" duration-ms="11127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadPage -->
        <test-method is-config="true" signature="configLogger()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:25Z" name="configLogger" finished-at="2018-05-30T09:20:26Z" duration-ms="103" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configLogger -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:26Z" name="reload" finished-at="2018-05-30T09:20:26Z" duration-ms="365" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="ipPhoneFunctionalities()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:26Z" name="ipPhoneFunctionalities" finished-at="2018-05-30T09:20:35Z" duration-ms="9510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ipPhoneFunctionalities -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:35Z" name="logSeparator" finished-at="2018-05-30T09:20:35Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:35Z" name="reload" finished-at="2018-05-30T09:20:36Z" duration-ms="461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="ipPhoneLogonCredentials()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:36Z" name="ipPhoneLogonCredentials" finished-at="2018-05-30T09:20:45Z" duration-ms="8725" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ipPhoneLogonCredentials -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:45Z" name="logSeparator" finished-at="2018-05-30T09:20:45Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:45Z" name="reload" finished-at="2018-05-30T09:20:45Z" duration-ms="581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="ipPhoneLogonErrorMessage()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:45Z" name="ipPhoneLogonErrorMessage" finished-at="2018-05-30T09:20:53Z" duration-ms="8203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ipPhoneLogonErrorMessage -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:53Z" name="reload" finished-at="2018-05-30T09:20:54Z" duration-ms="487" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:53Z" name="logSeparator" finished-at="2018-05-30T09:20:53Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method signature="ipPhoneOther()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:20:54Z" name="ipPhoneOther" finished-at="2018-05-30T09:21:02Z" duration-ms="8357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ipPhoneOther -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:02Z" name="logSeparator" finished-at="2018-05-30T09:21:02Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:02Z" name="reload" finished-at="2018-05-30T09:21:03Z" duration-ms="608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportBPC()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:03Z" name="reportBPC" finished-at="2018-05-30T09:21:11Z" duration-ms="8013" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportBPC -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:11Z" name="logSeparator" finished-at="2018-05-30T09:21:11Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:11Z" name="reload" finished-at="2018-05-30T09:21:11Z" duration-ms="448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportCitrixOneApp()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:11Z" name="reportCitrixOneApp" finished-at="2018-05-30T09:21:20Z" duration-ms="8262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCitrixOneApp -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:20Z" name="logSeparator" finished-at="2018-05-30T09:21:20Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:20Z" name="reload" finished-at="2018-05-30T09:21:20Z" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportCitrixOtherOneApp()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:20Z" name="reportCitrixOtherOneApp" finished-at="2018-05-30T09:21:30Z" duration-ms="9963" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCitrixOtherOneApp -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:30Z" name="logSeparator" finished-at="2018-05-30T09:21:30Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:30Z" name="reload" finished-at="2018-05-30T09:21:31Z" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportCitrixOtherSeveralApps()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:31Z" name="reportCitrixOtherSeveralApps" finished-at="2018-05-30T09:21:40Z" duration-ms="8988" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCitrixOtherSeveralApps -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:40Z" name="logSeparator" finished-at="2018-05-30T09:21:40Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:40Z" name="reload" finished-at="2018-05-30T09:21:40Z" duration-ms="223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportCitrixSeveralApps()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:40Z" name="reportCitrixSeveralApps" finished-at="2018-05-30T09:21:46Z" duration-ms="6496" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCitrixSeveralApps -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:46Z" name="logSeparator" finished-at="2018-05-30T09:21:46Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:46Z" name="reload" finished-at="2018-05-30T09:21:46Z" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportClickView()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:46Z" name="reportClickView" finished-at="2018-05-30T09:21:53Z" duration-ms="6853" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportClickView -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:53Z" name="logSeparator" finished-at="2018-05-30T09:21:53Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:53Z" name="reload" finished-at="2018-05-30T09:21:54Z" duration-ms="499" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportClockWorks()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:54Z" name="reportClockWorks" finished-at="2018-05-30T09:21:55Z" duration-ms="1405" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 358). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 358). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at model.Chatbot.clickButton(Chatbot.java:82)
at utilities.NavigationTree.clickButton(NavigationTree.java:95)
at utilities.NavigationTree.clickButton(NavigationTree.java:94)
at testcases.TestReportIncident.reportClockWorks(TestReportIncident.java:680)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportClockWorks -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:55Z" name="logSeparator" finished-at="2018-05-30T09:21:55Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:55Z" name="reload" finished-at="2018-05-30T09:21:55Z" duration-ms="211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportLyris()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:21:55Z" name="reportLyris" finished-at="2018-05-30T09:22:02Z" duration-ms="6821" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportLyris -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:02Z" name="logSeparator" finished-at="2018-05-30T09:22:02Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:02Z" name="reload" finished-at="2018-05-30T09:22:03Z" duration-ms="220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportMailChimp()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:03Z" name="reportMailChimp" finished-at="2018-05-30T09:22:30Z" duration-ms="27920" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportMailChimp(TestReportIncident.java:642)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportMailChimp -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:30Z" name="logSeparator" finished-at="2018-05-30T09:22:30Z" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:30Z" name="reload" finished-at="2018-05-30T09:22:31Z" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportMobaTime()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:31Z" name="reportMobaTime" finished-at="2018-05-30T09:22:55Z" duration-ms="24066" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportMobaTime(TestReportIncident.java:619)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportMobaTime -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:55Z" name="logSeparator" finished-at="2018-05-30T09:22:55Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:55Z" name="reload" finished-at="2018-05-30T09:22:55Z" duration-ms="351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportOfficeAppIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:55Z" name="reportOfficeAppIncident" finished-at="2018-05-30T09:22:57Z" duration-ms="1335" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 286). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 286). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at model.Chatbot.clickButton(Chatbot.java:82)
at utilities.NavigationTree.clickButton(NavigationTree.java:95)
at utilities.NavigationTree.clickButton(NavigationTree.java:94)
at testcases.TestReportIncident.reportOfficeAppIncident(TestReportIncident.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportOfficeAppIncident -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:57Z" name="reload" finished-at="2018-05-30T09:22:57Z" duration-ms="251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:57Z" name="logSeparator" finished-at="2018-05-30T09:22:57Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method signature="reportProConcept()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:22:57Z" name="reportProConcept" finished-at="2018-05-30T09:23:03Z" duration-ms="6023" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportProConcept -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:03Z" name="logSeparator" finished-at="2018-05-30T09:23:03Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:03Z" name="reload" finished-at="2018-05-30T09:23:03Z" duration-ms="228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportScorecards()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:03Z" name="reportScorecards" finished-at="2018-05-30T09:23:26Z" duration-ms="22584" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportScorecards(TestReportIncident.java:550)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportScorecards -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:26Z" name="logSeparator" finished-at="2018-05-30T09:23:26Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:26Z" name="reload" finished-at="2018-05-30T09:23:26Z" duration-ms="386" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportSkypeCredentials()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:26Z" name="reportSkypeCredentials" finished-at="2018-05-30T09:23:28Z" duration-ms="1647" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 294). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 294). Other element would receive the click: <p>...</p>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at model.Chatbot.clickButton(Chatbot.java:82)
at utilities.NavigationTree.clickButton(NavigationTree.java:95)
at utilities.NavigationTree.clickButton(NavigationTree.java:94)
at testcases.TestReportIncident.reportSkypeCredentials(TestReportIncident.java:392)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSkypeCredentials -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:28Z" name="logSeparator" finished-at="2018-05-30T09:23:28Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:28Z" name="reload" finished-at="2018-05-30T09:23:28Z" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportSkypeErrorMessage()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:28Z" name="reportSkypeErrorMessage" finished-at="2018-05-30T09:23:35Z" duration-ms="7461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSkypeErrorMessage -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:35Z" name="logSeparator" finished-at="2018-05-30T09:23:35Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:35Z" name="reload" finished-at="2018-05-30T09:23:36Z" duration-ms="221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportSkypeFunctionalities()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:23:36Z" name="reportSkypeFunctionalities" finished-at="2018-05-30T09:24:03Z" duration-ms="27833" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportSkypeFunctionalities(TestReportIncident.java:352)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSkypeFunctionalities -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:03Z" name="reload" finished-at="2018-05-30T09:24:04Z" duration-ms="468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:03Z" name="logSeparator" finished-at="2018-05-30T09:24:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method signature="reportSkypeOther()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:04Z" name="reportSkypeOther" finished-at="2018-05-30T09:24:32Z" duration-ms="27703" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportSkypeOther(TestReportIncident.java:377)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSkypeOther -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:32Z" name="logSeparator" finished-at="2018-05-30T09:24:32Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:32Z" name="reload" finished-at="2018-05-30T09:24:32Z" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportCitrixOtherAllApps()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:32Z" name="reportCitrixOtherAllApps" finished-at="2018-05-30T09:24:33Z" duration-ms="1492" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 350). Other element would receive the click: <button class="choiceBtn" ng-click="vm.sendChoice('security')">...</button>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <button class="choiceBtn" ng-click="vm.sendChoice('software')">...</button> is not clickable at point (320, 350). Other element would receive the click: <button class="choiceBtn" ng-click="vm.sendChoice('security')">...</button>
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'LBNL03409', ip: '10.32.61.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\SDECORTE\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 66.0.3359.181, webStorageEnabled: true}
Session ID: 8274e82f8607967f22b6963f1e045480
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
at model.Chatbot.clickButton(Chatbot.java:82)
at utilities.NavigationTree.clickButton(NavigationTree.java:95)
at utilities.NavigationTree.clickButton(NavigationTree.java:94)
at testcases.TestReportIncident.reportCitrixOtherAllApps(TestReportIncident.java:315)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportCitrixOtherAllApps -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:33Z" name="logSeparator" finished-at="2018-05-30T09:24:33Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
        <test-method is-config="true" signature="reload()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:33Z" name="reload" finished-at="2018-05-30T09:24:34Z" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reload -->
        <test-method signature="reportHRForms()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:34Z" name="reportHRForms" finished-at="2018-05-30T09:24:51Z" duration-ms="17788" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcases.TestReportIncident.reportHRForms(TestReportIncident.java:573)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportHRForms -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="closeDriver" finished-at="2018-05-30T09:24:52Z" duration-ms="896" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method signature="reportWordIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="reportWordIncident" depends-on-groups="officeapp" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestReportIncident.reportWordIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestReportIncident.reportWordIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportWordIncident -->
        <test-method signature="reportPowerpointIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="reportPowerpointIncident" depends-on-groups="officeapp" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestReportIncident.reportPowerpointIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestReportIncident.reportPowerpointIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportPowerpointIncident -->
        <test-method signature="reportOutlookIncidentBrowser()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="reportOutlookIncidentBrowser" depends-on-groups="officeapp" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestReportIncident.reportOutlookIncidentBrowser()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestReportIncident.reportOutlookIncidentBrowser()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportOutlookIncidentBrowser -->
        <test-method is-config="true" signature="logStuff()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="logStuff" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logStuff -->
        <test-method signature="reportExcelIncident()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="reportExcelIncident" depends-on-groups="officeapp" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestReportIncident.reportExcelIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestReportIncident.reportExcelIncident()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportExcelIncident -->
        <test-method signature="reportOutlookIncidentIcon()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="reportOutlookIncidentIcon" depends-on-groups="officeapp" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestReportIncident.reportOutlookIncidentIcon()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestReportIncident.reportOutlookIncidentIcon()[pri:0, instance:testcases.TestReportIncident@7690781] depends on not successfully finished methods in group "officeapp"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportOutlookIncidentIcon -->
        <test-method is-config="true" signature="logSeparator()[pri:0, instance:testcases.TestReportIncident@7690781]" started-at="2018-05-30T09:24:51Z" name="logSeparator" finished-at="2018-05-30T09:24:51Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logSeparator -->
      </class> <!-- testcases.TestReportIncident -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
